services:
  developer-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextmavens-developer-portal
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "3006:3000"
    restart: unless-stopped
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.portal-nextmavens.rule=Host(`portal.nextmavens.cloud`)
      - traefik.http.routers.portal-nextmavens.entrypoints=websecure
      - traefik.http.routers.portal-nextmavens.tls.certresolver=letsencrypt
      - traefik.http.routers.portal-nextmavens.priority=100
      - traefik.http.routers.portal-nextmavens.service=portal-nextmavens-service
      - traefik.http.services.portal-nextmavens-service.loadbalancer.server.port=3000

networks:
  dokploy-network:
    external: true
